# Generated by Django 3.2.9 on 2021-12-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='accepted',
        ),
        migrations.AddField(
            model_name='debt',
            name='from_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_debt', to='debts.debtrequest'),
        ),
        migrations.AddField(
            model_name='debtrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
