# Generated by Django 3.2.9 on 2021-12-22 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debt_from_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='from_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_connected_debt', to='debts.debtrequest'),
        ),
    ]
