# Generated by Django 4.0 on 2022-02-09 06:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_alter_debt_from_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDebtRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='closed_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_from_debt', related_query_name='from_debt', to='debts.closeddebtrequest'),
        ),
    ]
